name: CodeCov
on: [push, pull_request]
jobs:
  run:
    - name: Generate Report
      run: |
        pip install coverage
        coverage run -m unittest
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3